# waypoints_left.yaml
waypoints:
  - name: "waypoint_goal_1"
    x: 0.0
    y: 0.3
    z: 0.0
    yaw: 1.57
  - name: "waypoint_goal_2"
    x: 0.85
    y: 0.3
    z: 0.0
    yaw: 0.0
  - name: "waypoint_goal_3"
    x: 0.85
    y: 2.05
    z: 0.0
    yaw: 1.57
  - name: "place_goal_1"
    x: 0.85
    y: 5.27
    z: 0.0
    yaw: 1.57
  - name: "place_goal_2"
    x: 0.40
    y: 5.27
    z: 0.0
    yaw: 3.14
  - name: "place_goal_3"
    x: -0.40
    y: 5.27
    z: 0.0
    yaw: -2.62
  - name: "place_goal_4"
    x: -0.85
    y: 2.2
    z: 0.0
    yaw: -1.57
  - name: "waypoint_goal_4"
    x: -0.85
    y: 2.05
    z: 0.0
    yaw: -0.35