dog_perception:
  ros__parameters:
    image_topic: "/camera/image_raw"
    box_yolo_model_path: "boxes_detector.pt"
    box_confidence_threshold: 0.35
    box_nms_threshold: 0.45
    box_max_detections: 16
    box_class_names: ["food", "tool", "instrument", "medical"]
